homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 103
  unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Name of the location where Home Assistant is running
  name: _
  customize: !include customize.yaml

frontend:

http: 
 api_password: !secret http_password
  # Set to 1 to enable development mode
  # development: 1
 #sessions_enabled: 0
 trusted_networks:
   - 127.0.0.1
   - 192.168.1.2
   - 192.168.1.3
   - 192.168.1.4
   - 192.168.1.5
   - 192.168.1.6
   - 192.168.1.7
   - 192.168.1.8
   - 192.168.1.9
   - 192.168.1.10
   - 192.168.1.11
   - 192.168.1.12
   - 192.168.1.13
   - 192.168.1.14
   - 192.168.1.15
   - 192.168.1.16
   - 192.168.1.17
   - 192.168.1.18
   - 192.168.1.19
   - 192.168.1.20
   - 192.168.1.21
 ip_ban_enabled: True
 login_attempts_threshold: 5

recorder:
  purge_days: 2
#  db_url: sqlite:///home/dahoiv/hass.db

logbook:

restore_states:

logger:
  default: warn
  logs:
    custom_components.switch.broadlink: info
#    homeassistant.components.device_tracker: info
#    homeassistant.components.http: info
#    homeassistant.components.rfxtrx: debug
#    homeassistant.components.sensor.miflora: debug

history: 

#updater:

sun:

script: !include scripts.yaml

scene: !include scenes.yaml

automation: !include_dir_merge_list automation

light: !include lights.yaml

input_slider: !include input_slider.yaml

binary_sensor: !include binary_sensor.yaml

sensor: !include sensors.yaml

switch: !include switches.yaml

group: !include group.yaml

movement_light_gang:

movement_light_do:

update_ip:

proximity:
  home: 
    devices:
      - device_tracker.daniel
    tolerance: 50
    unit_of_measurement: m

notify:
  platform: pushbullet
  api_key: !secret pushbullet
  name: pushbullet

device_tracker:
- platform: nmap_tracker
  hosts: 192.168.1.1-255
  track_new_devices: no
  consider_home: 900
  interval_seconds: 10
  home_interval: 5
  scan_options: " --privileged -sP "
  # sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap 

#- platform: luci
#  host: 192.168.1.1
#  username: root
#  password: 
#  track_new_devices: no
#  consider_home: 900
#  interval_seconds: 10

- platform: bluetooth_tracker

- platform: gpslogger
  consider_home: 1800
  # http://:8123/api/gpslogger?api_password=XXX&latitude=%LAT&longitude=%LON&battery=%BATT&device=daniel&accuracy=%ACC

media_player:
- platform: cast
  host: 192.168.1.160

- platform: vlc
  name: Stue

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1Y0NJGR-if00-port0
  debug: False
  dummy: False

climate:
- platform: generic_thermostat
  name :  Termostat stue
  heater :  switch.ovn_stue
  target_sensor : sensor.mean_stue_temp
  target_temp : 18
  min_temp : 10
  max_temp : 25

- platform: generic_thermostat
  name :  Soverom
  heater :  switch.ovn_soverom
  target_sensor : sensor.Soverom_temperature
  target_temp : 15
  min_temp : 7
  max_temp : 25

#-  platform: generic_thermostat
# name :  Slow cooker
# heater :  switch.Slow_cooker
# target_sensor : sensor.temperature_rubicson_61951
# max_temp : 100

input_boolean: 
  movement3:
    initial: off
  movement_soverom:
    initial: off
  auto_heat:
    name: Auto heat
    initial: off
  tine_home:
    name: Tine hjemme
    initial: off

sensor miflora1:
  platform: miflora
  mac: C4:7C:8D:61:7E:3B 
  name: Blomst tv
  force_update: false
  median: 3
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity
   - battery

sensor miflora2:
  platform: miflora
  mac: C4:7C:8D:61:7F:EC 
  name: Blomst sofa
  force_update: false
  median: 3
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity
   - battery

sensor miflora3:
  platform: miflora
  mac: C4:7C:8D:61:7E:5D 
  name: Blomst bokhylle
  force_update: false
  median: 3
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity
   - battery

input_select:
  radio_stue:
    name: Radio
    options:
     - P3
     - P1
     - Alltid Nyheter
     - Av
    initial: Av
    icon: mdi:music-note
