- alias: "steketermometer fisk"
  trigger:
   - platform: state
     entity_id: input_select.steketermometer
     state: 'Fisk (50*)'
  action:
  - service: input_slider.select_value
    data:
      entity_id: "input_slider.temp_steketermometer"
      value: "50"
        
- alias: "steketermometer kylling"
  trigger:
   - platform: state
     entity_id: input_select.steketermometer
     state: 'Kylling (70*)'
  action:
  - service: input_slider.select_value
    data:
      entity_id: "input_slider.temp_steketermometer"
      value: "70"
